/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.addon.manager.gui;

import java.awt.Font;
import java.util.ResourceBundle;
import org.jspecify.annotations.NullMarked;
import javax.swing.ImageIcon;
import javax.swing.JList;
import org.exbin.jaguif.App;
import org.exbin.jaguif.addon.manager.api.ItemRecord;
import org.exbin.jaguif.language.api.LanguageModuleApi;

/**
 * Component for list of packs / addon suites.
 */
@NullMarked
public class AddonItemComponent extends javax.swing.JPanel {

    protected final ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(AddonItemComponent.class);
    protected final ImageIcon defaultItemIcon;
    protected final ImageIcon disabledStateIcon;
    protected final ImageIcon updateAvailableStateIcon;

    public AddonItemComponent() {
        defaultItemIcon = new ImageIcon(getClass().getResource(resourceBundle.getString("defaultItem.icon")));
        disabledStateIcon = new ImageIcon(getClass().getResource(resourceBundle.getString("disabledState.icon")));
        updateAvailableStateIcon = new ImageIcon(getClass().getResource(resourceBundle.getString("updateAvailableState.icon")));
        initComponents();
    }

    public void setItemRecord(JList<?> list, ItemRecord itemRecord, boolean isSelected, boolean cellHasFocus) {
        nameLabel.setText(itemRecord.getName());
        iconLabel.setIcon(itemRecord.getIcon().orElse(defaultItemIcon));
        providerLabel.setText(itemRecord.getProvider().orElse(""));

        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }
        if (!itemRecord.isEnabled()) {
            stateLabel.setIcon(disabledStateIcon);
            setToolTipText(resourceBundle.getString("disabledState.toolTip"));
        } else if (itemRecord.isUpdateAvailable()) {
            stateLabel.setIcon(updateAvailableStateIcon);
            setToolTipText(resourceBundle.getString("updateAvailableState.toolTip"));
        } else {
            stateLabel.setIcon(null);
            setToolTipText(null);
        }
    }

    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        providerLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exbin/jaguif/addon/manager/resources/icons/48px/puzzle.png"))); // NOI18N

        nameLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        nameLabel.setText("Addon Name");

        providerLabel.setFont(getFont().deriveFont(Font.PLAIN));
        providerLabel.setText("Provider");

        stateLabel.setPreferredSize(new java.awt.Dimension(16, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(iconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(providerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconLabel)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(providerLabel)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel providerLabel;
    private javax.swing.JLabel stateLabel;
    // End of variables declaration//GEN-END:variables

}
