/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.addon.manager.gui;

import java.awt.Font;
import java.util.ResourceBundle;
import org.jspecify.annotations.NullMarked;
import javax.swing.ImageIcon;
import javax.swing.JList;
import org.exbin.jaguif.App;
import org.exbin.jaguif.addon.manager.api.AddonOperation;
import org.exbin.jaguif.addon.manager.api.ItemRecord;
import org.exbin.jaguif.language.api.LanguageModuleApi;

/**
 * Component for list of cart operations.
 */
@NullMarked
public class AddonCartComponent extends javax.swing.JPanel {

    protected final ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(AddonCartComponent.class);
    protected final ImageIcon defaultItemIcon;
    protected final ImageIcon installVariantIcon;
    protected final ImageIcon updateVariantIcon;
    protected final ImageIcon removeVariantIcon;

    public AddonCartComponent() {
        defaultItemIcon = new ImageIcon(getClass().getResource(resourceBundle.getString("defaultItem.icon")));
        installVariantIcon = new ImageIcon(getClass().getResource(resourceBundle.getString("installVariant.icon")));
        updateVariantIcon = new ImageIcon(getClass().getResource(resourceBundle.getString("updateVariant.icon")));
        removeVariantIcon = new ImageIcon(getClass().getResource(resourceBundle.getString("removeVariant.icon")));
        initComponents();
    }

    public void setCartRecord(JList<?> list, AddonOperation addonOperation, boolean isSelected, boolean cellHasFocus) {
        ItemRecord itemRecord = addonOperation.getItem();
        nameLabel.setText(itemRecord.getName());
        iconLabel.setIcon(itemRecord.getIcon().orElse(defaultItemIcon));
        providerLabel.setText(itemRecord.getProvider().orElse(""));

        if (isSelected) {
            setBackground(list.getSelectionBackground());
            setForeground(list.getSelectionForeground());
        } else {
            setBackground(list.getBackground());
            setForeground(list.getForeground());
        }
        switch (addonOperation.getVariant()) {
            case INSTALL:
                variantLabel.setIcon(installVariantIcon);
                setToolTipText(resourceBundle.getString("installVariant.toolTip"));
                break;
            case UPDATE:
                variantLabel.setIcon(updateVariantIcon);
                setToolTipText(resourceBundle.getString("updateVariant.toolTip"));
                break;
            case REMOVE:
                variantLabel.setIcon(removeVariantIcon);
                setToolTipText(resourceBundle.getString("removeVariant.toolTip"));
                break;
            default:
                throw new AssertionError();
        }
    }

    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        variantLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        providerLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));

        variantLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        variantLabel.setToolTipText("");

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exbin/jaguif/addon/manager/resources/icons/48px/puzzle.png"))); // NOI18N

        nameLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        nameLabel.setText("Addon Name");

        providerLabel.setFont(getFont().deriveFont(Font.PLAIN));
        providerLabel.setText("Provider");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(variantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(providerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(providerLabel))
            .addComponent(variantLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel providerLabel;
    private javax.swing.JLabel variantLabel;
    // End of variables declaration//GEN-END:variables

}
