/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.action.manager.settings.gui;

import java.awt.BorderLayout;
import java.util.List;
import java.util.ResourceBundle;
import org.jspecify.annotations.NullMarked;
import org.exbin.jaguif.App;
import org.exbin.jaguif.action.manager.gui.KeyMapTablePanel;
import org.exbin.jaguif.action.manager.model.KeyMapRecord;
import org.exbin.jaguif.language.api.LanguageModuleApi;
import org.exbin.jaguif.options.settings.api.SettingsComponent;
import org.exbin.jaguif.options.settings.api.SettingsModifiedListener;
import org.exbin.jaguif.options.settings.api.SettingsOptionsProvider;

/**
 * Keymap settings panel.
 */
@NullMarked
public class KeyMapSettingsPanel extends javax.swing.JPanel implements SettingsComponent {

    protected final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(KeyMapSettingsPanel.class);

    protected SettingsModifiedListener settingsModifiedListener;
    protected final KeyMapTablePanel keyMap = new KeyMapTablePanel();

    public KeyMapSettingsPanel() {
        initComponents();
        init();
    }

    private void init() {
        add(keyMap, BorderLayout.CENTER);
    }

    @Override
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public void setRecords(List<KeyMapRecord> records) {
        keyMap.setRecords(records);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void loadFromOptions(SettingsOptionsProvider settingsOptionsProvider) {
    }

    @Override
    public void saveToOptions(SettingsOptionsProvider settingsOptionsProvider) {
    }

    private void notifyModified() {
        if (settingsModifiedListener != null) {
            settingsModifiedListener.notifyModified();
        }
    }

    @Override
    public void setSettingsModifiedListener(SettingsModifiedListener listener) {
        settingsModifiedListener = listener;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
