rootProject.name = 'jaguif'

include ":deps"

include ":core:jaguif-core"
include ":core:jaguif-basic"
include ":core:jaguif-addon"
include ":modules:jaguif-context-api"
include ":modules:jaguif-context"
include ":modules:jaguif-contribution-api"
include ":modules:jaguif-contribution"
include ":modules:jaguif-action-api"
include ":modules:jaguif-action"
include ":modules:jaguif-action-manager"
include ":modules:jaguif-menu-api"
include ":modules:jaguif-menu"
include ":modules:jaguif-menu-popup-api"
include ":modules:jaguif-menu-popup"
include ":modules:jaguif-toolbar-api"
include ":modules:jaguif-toolbar"
include ":modules:jaguif-statusbar-api"
include ":modules:jaguif-statusbar"
include ":modules:jaguif-sidebar-api"
include ":modules:jaguif-sidebar"
include ":modules:jaguif-tabpages-api"
include ":modules:jaguif-tabpages"
include ":modules:jaguif-ui"
include ":modules:jaguif-ui-api"
include ":modules:jaguif-ui-theme-api"
include ":modules:jaguif-ui-theme"
include ":modules:jaguif-window-api"
include ":modules:jaguif-window"
include ":modules:jaguif-frame-api"
include ":modules:jaguif-frame"
include ":modules:jaguif-document-api"
include ":modules:jaguif-document"
include ":modules:jaguif-document-recent"
include ":modules:jaguif-document-text"
include ":modules:jaguif-document-syntax"
include ":modules:jaguif-file-api"
include ":modules:jaguif-file"
include ":modules:jaguif-component-api"
include ":modules:jaguif-component"
include ":modules:jaguif-operation-api"
include ":modules:jaguif-operation"
include ":modules:jaguif-operation-undo-api"
include ":modules:jaguif-operation-undo"
include ":modules:jaguif-operation-manager-api"
include ":modules:jaguif-operation-manager"
include ":modules:jaguif-print-api"
include ":modules:jaguif-print"
include ":modules:jaguif-progress-api"
include ":modules:jaguif-progress"
include ":modules:jaguif-notification-api"
include ":modules:jaguif-notification"
include ":modules:jaguif-help-api"
include ":modules:jaguif-help"
include ":modules:jaguif-help-local"
include ":modules:jaguif-help-online-api"
include ":modules:jaguif-help-online"
include ":modules:jaguif-options-api"
include ":modules:jaguif-options"
include ":modules:jaguif-options-settings-api"
include ":modules:jaguif-options-settings"
include ":modules:jaguif-utils"
include ":modules:jaguif-license-api"
include ":modules:jaguif-license"
include ":modules:jaguif-language-api"
include ":modules:jaguif-language"
include ":modules:jaguif-addon-update-api"
include ":modules:jaguif-addon-update"
include ":modules:jaguif-addon-manager-api"
include ":modules:jaguif-addon-manager"
include ":modules:jaguif-addon-catalog-api"
include ":modules:jaguif-addon-catalog"
include ":modules:jaguif-addon-packs"
include ":modules:jaguif-docking-api"
include ":modules:jaguif-docking"
include ":modules:jaguif-docking-multi-api"
include ":modules:jaguif-docking-multi"
include ":modules:jaguif-project-api"
include ":modules:jaguif-project"
include ":modules:jaguif-search-api"
include ":modules:jaguif-search"
include ":modules:jaguif-search-area-api"
include ":modules:jaguif-search-area"
include ":modules:jaguif-text-encoding"
include ":modules:jaguif-text-font"

File placeholder = file("deps/.downloaded")
if (placeholder.exists()) {
    placeholder.delete()
}

if (!gradle.startParameter.taskNames.contains("clean") || gradle.startParameter.projectProperties.containsKey("moduleDep")) {
    File depsDir = file("deps")
    // Include all downloaded dependency modules
    depsDir.listFiles().each() { childFile ->
        if (childFile.isDirectory() && childFile.name != ".gradle") {
            include ':deps:' + childFile.name
        }
    }
}

gradle.allprojects {
  ext {
    depsRoot = 'Jaguif'
  }
}

