findInFilesAction.text=Find in Files
findInFilesAction.shortDescription=Find words in text
findInFilesAction.smallIcon=/org/exbin/jaguif/search/resources/icons/16px/edit-find.png
replaceInFilesAction.text=Replace in Files
replaceInFilesAction.shortDescription=Find and replace given string for another
replaceInFilesAction.smallIcon=/org/exbin/jaguif/search/resources/icons/16px/edit-find-replace.png
