saveModifiedQuestion.title=Save File?
saveModifiedQuestion.message=Document was modified! Do you wish to save it?
saveModifiedQuestion.action_save=Save
saveModifiedQuestion.action_discard=Discard
saveModifiedQuestion.action_cancel=Cancel
overwriteFileQuestion.title=Overwrite File?
overwriteFileQuestion.message=This file already exists! Do you wish to overwrite it?
overwriteFileQuestion.action_save=Overwrite
overwriteFileQuestion.action_cancel=Cancel
unableToSaveMessage.title=Unable to save file
unableToSaveMessage.message=Unable to save file: %s
fileNotFound.title=File not found
fileNotFound.message=Unable to load file: %s
AllFilesFilter.description=All files (*)
SaveAsDialog.title=Save As
fileDialogs.swing=Default (Swing)
fileDialogs.awt=Native (AWT)
settingsPage.file.name=File
