/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.addon.manager.operation.gui;

import java.util.ResourceBundle;
import org.jspecify.annotations.NullMarked;
import javax.swing.DefaultListModel;
import org.exbin.jaguif.App;
import org.exbin.jaguif.language.api.LanguageModuleApi;

/**
 * Panel for addon installation / update operation.
 */
@NullMarked
public class AddonOperationOverviewPanel extends javax.swing.JPanel {

    protected final ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(AddonOperationOverviewPanel.class);

    public AddonOperationOverviewPanel() {
        initComponents();
        init();
    }

    private void init() {
        operationsList.setModel(new DefaultListModel<>());
    }

    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public void addOperation(String operation) {
        DefaultListModel<String> model = (DefaultListModel<String>) operationsList.getModel();
        model.addElement(operation);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operationsLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        operationsList = new javax.swing.JList<>();

        operationsLabel.setText(resourceBundle.getString("operationsLabel.text")); // NOI18N

        scrollPane.setViewportView(operationsList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(operationsLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operationsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel operationsLabel;
    private javax.swing.JList<String> operationsList;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

}
