/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.addon.manager.operation.gui;

import java.awt.BorderLayout;
import java.util.Optional;
import java.util.ResourceBundle;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.NullMarked;
import javax.swing.JComponent;
import org.exbin.jaguif.App;
import org.exbin.jaguif.addon.manager.operation.AddonModificationStep;
import org.exbin.jaguif.language.api.LanguageModuleApi;

/**
 * Panel for addon installation / update operation.
 */
@NullMarked
public class AddonOperationPanel extends javax.swing.JPanel {

    protected final ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(AddonOperationPanel.class);

    protected final AddonOperationOverviewPanel overviewPanel = new AddonOperationOverviewPanel();
    protected final AddonOperationLicensePanel licensePanel = new AddonOperationLicensePanel();
    protected final AddonOperationDownloadPanel downloadPanel = new AddonOperationDownloadPanel();
    protected final AddonOperationSuccessPanel successPanel = new AddonOperationSuccessPanel();

    protected JComponent activePanel = null;

    public AddonOperationPanel() {
        initComponents();
        init();
    }

    private void init() {
        goToStep(AddonModificationStep.OVERVIEW);
    }

    @NonNull
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public void goToStep(AddonModificationStep step) {
        if (activePanel != null) {
            remove(activePanel);
        }

        switch (step) {
            case OVERVIEW:
                activePanel = overviewPanel;
                break;
            case LICENSE:
                activePanel = licensePanel;
                break;
            case DOWNLOAD:
                activePanel = downloadPanel;
                break;
            case SUCCESS:
                activePanel = successPanel;
                break;
            default:
                throw new AssertionError();
        }

        add(activePanel, BorderLayout.CENTER);
        revalidate();
        repaint();
    }

    @NonNull
    public Optional<JComponent> getActiveComponent() {
        return Optional.ofNullable(activePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
