rootProject.name = 'jaguif-docking-multi'

if (rootProject.path == ':') {
    include ':core:jaguif-core'
    include ':modules:jaguif-docking-multi-api'
    include ':modules:jaguif-docking-api'
    include ':modules:jaguif-docking'
    include ':modules:jaguif-contribution-api'
    include ':modules:jaguif-context-api'
    include ':modules:jaguif-action-api'
    include ':modules:jaguif-document-api'
    include ':modules:jaguif-menu-api'
    include ':modules:jaguif-toolbar-api'
    include ':modules:jaguif-window-api'
    include ':modules:jaguif-ui-api'
    include ':modules:jaguif-file-api'
    include ':modules:jaguif-options-api'
    include ':modules:jaguif-options-settings-api'
    include ':modules:jaguif-language-api'
    include ':modules:jaguif-utils'

    include ':modules:jaguif-frame-api'
    include ':modules:jaguif-menu'
}

apply from: '../jaguif-modules-settings.gradle'
