/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.docking.gui;

import java.awt.BorderLayout;
import java.awt.Component;
import org.jspecify.annotations.Nullable;
import org.jspecify.annotations.NullMarked;

/**
 * Docking panel.
 */
@NullMarked
public class DockingPanel extends javax.swing.JPanel {

    protected Component sideToolBar = null;
    protected Component sideComponent = null;
    protected Component contentComponent = null;
    protected boolean sidePanelVisible = false;
    protected int dividerLocation = 300;

    public DockingPanel() {
        initComponents();
        init();
    }

    private void init() {
    }

    public void setContentComponent(@Nullable Component contentComponent) {
        if (this.contentComponent != null && !sidePanelVisible) {
            remove(this.contentComponent);
        }

        this.contentComponent = contentComponent;

        if (sidePanelVisible) {
            splitPane.setRightComponent(contentComponent);
        } else {
            if (contentComponent != null) {
                add(contentComponent, BorderLayout.CENTER);
            }
        }
        revalidate();
        repaint();
    }

    public void setSideToolBar(@Nullable Component sideToolBar) {
        if (this.sideToolBar == sideToolBar) {
            return;
        }

        if (this.sideToolBar != null) {
            remove(this.sideToolBar);
        }
        this.sideToolBar = sideToolBar;
        if (sideToolBar != null) {
            add(sideToolBar, BorderLayout.WEST);
        }
        revalidate();
        repaint();
    }

    public void setSideComponent(Component sideComponent) {
        this.sideComponent = sideComponent;
        if (sidePanelVisible) {
            splitPane.setLeftComponent(sideComponent);
        }
    }

    public boolean isSidePanelVisible() {
        return sidePanelVisible;
    }

    public void setSidePanelVisible(boolean visible) {
        if (sidePanelVisible == visible) {
            return;
        }

        if (sidePanelVisible) {
            dividerLocation = splitPane.getDividerLocation();
            remove(splitPane);
        } else {
            remove(contentComponent);
        }

        sidePanelVisible = visible;

        if (sidePanelVisible) {
            splitPane.setLeftComponent(sideComponent);
            splitPane.setRightComponent(contentComponent);
            add(splitPane, BorderLayout.CENTER);
            splitPane.setDividerLocation(dividerLocation);
        } else {
            add(contentComponent, BorderLayout.CENTER);
        }
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
