/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.frame.settings.gui;

import java.util.ResourceBundle;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.NullMarked;
import org.exbin.jaguif.App;
import org.exbin.jaguif.language.api.LanguageModuleApi;
import org.exbin.jaguif.utils.ComponentResourceProvider;
import org.exbin.jaguif.frame.settings.FrameAppearanceOptions;
import org.exbin.jaguif.options.settings.api.SettingsComponent;
import org.exbin.jaguif.options.settings.api.SettingsModifiedListener;
import org.exbin.jaguif.options.settings.api.SettingsOptionsProvider;

/**
 * Frame appearance settings panel.
 */
@NullMarked
public class FrameAppearanceSettingsPanel extends javax.swing.JPanel implements SettingsComponent, ComponentResourceProvider {

    protected final java.util.ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(FrameAppearanceSettingsPanel.class);

    protected SettingsModifiedListener settingsModifiedListener;

    public FrameAppearanceSettingsPanel() {
        initComponents();
    }

    @NonNull
    @Override
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    @Override
    public void loadFromOptions(SettingsOptionsProvider settingsOptionsProvider) {
        FrameAppearanceOptions options = settingsOptionsProvider.getSettingsOptions(FrameAppearanceOptions.class);
        showToolbarCheckBox.setSelected(options.isShowToolBar());
        showCaptionsCheckBox.setSelected(options.isShowToolBarCaptions());
        showStatusbarCheckBox.setSelected(options.isShowStatusBar());

        /* if (contextProvider != null) {
            ContextFrame contextFrame = contextProvider.getActiveState(ContextFrame.class);
            if (contextFrame instanceof ComponentFrame) {
                SettingsPanelUpdater updater = new SettingsPanelUpdater(this::notifyModified);
                ComponentFrame frame = (ComponentFrame) contextFrame;
                updater.setCheckBoxSelected(showToolbarCheckBox, frame.isToolBarVisible());
                updater.setCheckBoxSelected(showCaptionsCheckBox, frame.isToolBarCaptionsVisible());
                updater.setCheckBoxSelected(showStatusbarCheckBox, frame.isStatusBarVisible());
            }
        } */
    }

    @Override
    public void saveToOptions(SettingsOptionsProvider settingsOptionsProvider) {
        FrameAppearanceOptions options = settingsOptionsProvider.getSettingsOptions(FrameAppearanceOptions.class);
        options.setShowToolBar(showToolbarCheckBox.isSelected());
        options.setShowToolBarCaptions(showCaptionsCheckBox.isSelected());
        options.setShowStatusBar(showStatusbarCheckBox.isSelected());

        /* if (contextProvider != null) {
            ContextFrame contextFrame = contextProvider.getActiveState(ContextFrame.class);
            if (contextFrame instanceof ComponentFrame) {
                FrameAppearanceSettingsApplier applier = new FrameAppearanceSettingsApplier();
                applier.applySettings(contextFrame, settingsOptionsProvider);
                contextProvider.notifyStateChange(ContextFrame.class, ContextFrame.ChangeType.BARS_LAYOUT_CHANGE);
            }
        } */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showToolbarCheckBox = new javax.swing.JCheckBox();
        showCaptionsCheckBox = new javax.swing.JCheckBox();
        showStatusbarCheckBox = new javax.swing.JCheckBox();

        showToolbarCheckBox.setSelected(true);
        showToolbarCheckBox.setText(resourceBundle.getString("showToolbarCheckBox.text")); // NOI18N
        showToolbarCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showToolbarCheckBoxjCheckBoxItemStateChanged(evt);
            }
        });

        showCaptionsCheckBox.setSelected(true);
        showCaptionsCheckBox.setText(resourceBundle.getString("showCaptionsCheckBox.text")); // NOI18N
        showCaptionsCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showCaptionsCheckBoxjCheckBoxItemStateChanged(evt);
            }
        });

        showStatusbarCheckBox.setSelected(true);
        showStatusbarCheckBox.setText(resourceBundle.getString("showStatusbarCheckBox.text")); // NOI18N
        showStatusbarCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showStatusbarCheckBoxjCheckBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showCaptionsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showStatusbarCheckBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showToolbarCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showToolbarCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showCaptionsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showStatusbarCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showToolbarCheckBoxjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showToolbarCheckBoxjCheckBoxItemStateChanged
        notifyModified();
    }//GEN-LAST:event_showToolbarCheckBoxjCheckBoxItemStateChanged

    private void showCaptionsCheckBoxjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showCaptionsCheckBoxjCheckBoxItemStateChanged
        notifyModified();
    }//GEN-LAST:event_showCaptionsCheckBoxjCheckBoxItemStateChanged

    private void showStatusbarCheckBoxjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showStatusbarCheckBoxjCheckBoxItemStateChanged
        notifyModified();
    }//GEN-LAST:event_showStatusbarCheckBoxjCheckBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox showCaptionsCheckBox;
    private javax.swing.JCheckBox showStatusbarCheckBox;
    private javax.swing.JCheckBox showToolbarCheckBox;
    // End of variables declaration//GEN-END:variables

    private void notifyModified() {
        if (settingsModifiedListener != null) {
            settingsModifiedListener.notifyModified();
        }
    }

    @Override
    public void setSettingsModifiedListener(SettingsModifiedListener listener) {
        settingsModifiedListener = listener;
    }
}
