/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.action.manager.gui;

import java.util.List;
import org.jspecify.annotations.NullMarked;
import javax.swing.KeyStroke;
import org.exbin.jaguif.action.manager.model.KeyMapRecord;
import org.exbin.jaguif.action.manager.model.KeyMapTableModel;

/**
 * Keymap table panel.
 */
@NullMarked
public class KeyMapTablePanel extends javax.swing.JPanel {

    private final KeyMapTableModel tableModel = new KeyMapTableModel();

    public KeyMapTablePanel() {
        initComponents();
        init();
    }

    private void init() {
        keyMapTable.setModel(tableModel);
        keyMapTable.setDefaultRenderer(KeyMapRecord.class, new KeyMapTableTitleRenderer());
        keyMapTable.setDefaultRenderer(KeyStroke.class, new KeyMapTableKeyStrokeRenderer());
    }

    public void setRecords(List<KeyMapRecord> records) {
        tableModel.setRecords(records);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        keyMapTable = new javax.swing.JTable();

        keyMapTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPane.setViewportView(keyMapTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable keyMapTable;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
