/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.addon.update.settings.gui;

import java.util.ResourceBundle;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.NullMarked;
import org.exbin.jaguif.App;
import org.exbin.jaguif.language.api.LanguageModuleApi;
import org.exbin.jaguif.addon.update.settings.CheckForUpdateOptions;
import org.exbin.jaguif.options.settings.api.SettingsComponent;
import org.exbin.jaguif.options.settings.api.SettingsModifiedListener;
import org.exbin.jaguif.options.settings.api.SettingsOptionsProvider;

/**
 * Application update settings panel.
 */
@NullMarked
public class ApplicationUpdateSettingsPanel extends javax.swing.JPanel implements SettingsComponent {

    protected final ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(ApplicationUpdateSettingsPanel.class);

    protected SettingsModifiedListener settingsModifiedListener;
    
    public ApplicationUpdateSettingsPanel() {
        initComponents();
    }

    @NonNull
    @Override
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    @Override
    public void loadFromOptions(SettingsOptionsProvider settingsOptionsProvider) {
        CheckForUpdateOptions options = settingsOptionsProvider.getSettingsOptions(CheckForUpdateOptions.class);
        checkForUpdatesOnStartCheckBox.setSelected(options.isShouldCheckForUpdate());
    }

    @Override
    public void saveToOptions(SettingsOptionsProvider settingsOptionsProvider) {
        CheckForUpdateOptions options = settingsOptionsProvider.getSettingsOptions(CheckForUpdateOptions.class);
        options.setShouldCheckForUpdate(checkForUpdatesOnStartCheckBox.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkForUpdatesOnStartCheckBox = new javax.swing.JCheckBox();

        setName("Form"); // NOI18N

        checkForUpdatesOnStartCheckBox.setSelected(true);
        checkForUpdatesOnStartCheckBox.setText(resourceBundle.getString("checkForUpdatesOnStartCheckBox.text")); // NOI18N
        checkForUpdatesOnStartCheckBox.setName("checkForUpdatesOnStartCheckBox"); // NOI18N
        checkForUpdatesOnStartCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkForUpdatesOnStartCheckBoxjCheckBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkForUpdatesOnStartCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkForUpdatesOnStartCheckBox))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkForUpdatesOnStartCheckBoxjCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkForUpdatesOnStartCheckBoxjCheckBoxItemStateChanged
        notifyModified();
    }//GEN-LAST:event_checkForUpdatesOnStartCheckBoxjCheckBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkForUpdatesOnStartCheckBox;
    // End of variables declaration//GEN-END:variables

    private void notifyModified() {
        if (settingsModifiedListener != null) {
            settingsModifiedListener.notifyModified();
        }
    }

    @Override
    public void setSettingsModifiedListener(SettingsModifiedListener listener) {
        settingsModifiedListener = listener;
    }
}
