rootProject.name = 'jaguif-search-area-api'

if (rootProject.path == ':') {
    include ':core:jaguif-core'
    include ':modules:jaguif-contribution-api'
    include ':modules:jaguif-context-api'
    include ':modules:jaguif-action-api'
    include ':modules:jaguif-help-api'
    include ':modules:jaguif-menu-api'
    include ':modules:jaguif-menu-popup-api'
    include ':modules:jaguif-search-api'
    include ':modules:jaguif-frame-api'
    include ':modules:jaguif-language-api'
    include ':modules:jaguif-options-api'
    include ':modules:jaguif-utils'
    include ':modules:jaguif-window-api'
}

apply from: '../jaguif-modules-settings.gradle'
