dialog.title=Check for Update
header.title=Checks for newer version for update
header.description=Checks whether newer version of the application is available
header.icon=/org/exbin/jaguif/addon/update/resources/icons/48px/update-product.png

closeButton.text=Close
copyLinkMenuItem.text=Copy Link
availableVersionLabel.text=Available Application Version
currentVersionLabel.text=Current Application Version

unknown=unknown
status.checking.text=Checking for available updates...
status.checking.icon=/org/exbin/jaguif/addon/update/resources/icons/48px/internet-web-browser-7.png
status.updateUrlNotSet.text=URL for updates was not set!
status.updateUrlNotSet.icon=/org/exbin/jaguif/addon/update/resources/icons/48px/dialog-no.png
status.noConnection.text=Unable to connect!
status.noConnection.icon=/org/exbin/jaguif/addon/update/resources/icons/png/48px/dialog-no.png
status.connectionIssue.text=Connection issue during attempt to connect!
status.connectionIssue.icon=/org/exbin/jaguif/addon/update/resources/icons/48px/dialog-no.png
status.notFound.text=No update information on update website!
status.notFound.icon=/org/exbin/jaguif/addon/update/resources/icons/48px/dialog-no.png
status.noUpdateAvailable.text=No newer update available.
status.noUpdateAvailable.icon=/org/exbin/jaguif/addon/update/resources/icons/48px/dialog-ok-5.png
status.updateFound.text=Newer version is available!
status.updateFound.icon=/org/exbin/jaguif/addon/update/resources/icons/48px/upgrade_misc.png
status.misc.icon=/org/exbin/jaguif/addon/update/resources/icons/48px/upgrade_misc.png
downloadButton.text=Download
recheckButton.text=Recheck
statusTextLabel.text=Checking for available updates...
