/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.tabpages.gui;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import org.jspecify.annotations.NullMarked;
import javax.swing.Icon;
import javax.swing.JComponent;
import org.exbin.jaguif.tabpages.api.TabPages;
import org.exbin.jaguif.tabpages.api.TabPagesChangeListener;
import org.exbin.jaguif.tabpages.api.TabPagesComponent;

/**
 * Panel for multiple pages organized by tabs.
 */
@NullMarked
public class OptTabbedPagesPanel extends javax.swing.JPanel implements TabPages {

    protected final List<TabPagesChangeListener> pageChangeListeners = new ArrayList<>();
    protected int activeIndex = -1;
    protected TabPagesComponent firstPage = null;

    public OptTabbedPagesPanel() {
        initComponents();
        tabbedPane.addChangeListener((e) -> {
            int selectedIndex = tabbedPane.getSelectedIndex();
            changeActivePageIndex(selectedIndex);
        });
    }

    @Override
    public JComponent getComponent() {
        return this;
    }

    @Override
    public void addPage(TabPagesComponent page) {
        if (firstPage == null) {
            firstPage = page;
            activeIndex = 0;
            add(page.getComponent(), BorderLayout.CENTER);
        } else {
            if (tabbedPane.getComponentCount() == 0) {
                remove(firstPage.getComponent());
                add(tabbedPane, BorderLayout.CENTER);
                addTab(firstPage);
            }
            addTab(page);
        }
    }

    private void addTab(TabPagesComponent page) {
        String tabTitle = (String) page.getValue(TabPagesComponent.KEY_NAME);
        Icon tabIcon = (Icon) page.getValue(TabPagesComponent.KEY_ICON);
        String tabTooltip = (String) page.getValue(TabPagesComponent.KEY_TOOLTIP);
        tabbedPane.addTab(tabTitle, tabIcon, page.getComponent(), tabTooltip);
    }

    @Override
    public int getActivePageIndex() {
        return activeIndex;
    }

    @Override
    public void changeActivePageIndex(int index) {
        if (activeIndex != index) {
            activeIndex = index;
            notifyActiveIndexChanged();
        }
    }

    @Override
    public int getPagesCount() {
        if (tabbedPane.getComponentCount() == 0) {
            return firstPage == null ? 0 : 1;
        }

        return tabbedPane.getComponentCount();
    }

    @Override
    public void addPageChangeListener(TabPagesChangeListener listener) {
        pageChangeListeners.add(listener);
    }

    @Override
    public void removePageChangeListener(TabPagesChangeListener listener) {
        pageChangeListeners.remove(listener);
    }

    private void notifyActiveIndexChanged() {
        for (TabPagesChangeListener listener : pageChangeListeners) {
            listener.activeIndexChanged(activeIndex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        tabbedPane.setName("tabbedPane"); // NOI18N

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
