/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.file.settings.gui;

import java.awt.Component;
import java.util.List;
import java.util.ResourceBundle;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;
import org.jspecify.annotations.NullMarked;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import org.exbin.jaguif.App;
import org.exbin.jaguif.file.settings.FileOptions;
import org.exbin.jaguif.language.api.LanguageModuleApi;
import org.exbin.jaguif.options.settings.api.SettingsComponent;
import org.exbin.jaguif.options.settings.api.SettingsModifiedListener;
import org.exbin.jaguif.options.settings.api.SettingsOptionsProvider;

/**
 * Data inspector options panel.
 */
@NullMarked
public class FileSettingsPanel extends javax.swing.JPanel implements SettingsComponent {

    protected final ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(FileSettingsPanel.class);

    protected SettingsModifiedListener settingsModifiedListener;

    public FileSettingsPanel() {
        initComponents();
        init();
    }

    private void init() {
    }

    @NonNull
    @Override
    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public void setFileDialogs(List<String> fileDialogsKeys, List<String> fileDialogsNames) {
        DefaultComboBoxModel<String> fileDialogsComboBoxModel = new DefaultComboBoxModel<>();
        fileDialogsKeys.forEach((themeKey) -> {
            fileDialogsComboBoxModel.addElement(themeKey);
        });
        fileDialogsComboBox.setModel(fileDialogsComboBoxModel);
        fileDialogsComboBox.setRenderer(new DefaultListCellRenderer() {
            @NonNull
            @Override
            public Component getListCellRendererComponent(JList<?> list, @Nullable Object value, int index, boolean isSelected, boolean cellHasFocus) {
                if (index >= 0) {
                    return super.getListCellRendererComponent(list, fileDialogsNames.get(index), index, isSelected, cellHasFocus);
                }
                int selectedIndex = fileDialogsComboBox.getSelectedIndex();
                return super.getListCellRendererComponent(list, selectedIndex >= 0 ? fileDialogsNames.get(selectedIndex) : value, index, isSelected, cellHasFocus);
            }
        });
    }

    @Override
    public void loadFromOptions(SettingsOptionsProvider settingsOptionsProvider) {
        FileOptions options = settingsOptionsProvider.getSettingsOptions(FileOptions.class);
        fileDialogsComboBox.setSelectedIndex(findMatchingElement(fileDialogsComboBox.getModel(), options.getFileDialogs()));
    }

    @Override
    public void saveToOptions(SettingsOptionsProvider settingsOptionsProvider) {
        FileOptions options = settingsOptionsProvider.getSettingsOptions(FileOptions.class);
        options.setFileDialogs((String) fileDialogsComboBox.getSelectedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileDialogsLabel = new javax.swing.JLabel();
        fileDialogsComboBox = new javax.swing.JComboBox<>();

        setName("Form"); // NOI18N

        fileDialogsLabel.setText(resourceBundle.getString("fileDialogsLabel.text")); // NOI18N
        fileDialogsLabel.setName("fileDialogsLabel"); // NOI18N

        fileDialogsComboBox.setName("fileDialogsComboBox"); // NOI18N
        fileDialogsComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fileDialogsComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileDialogsLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fileDialogsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileDialogsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileDialogsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fileDialogsComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fileDialogsComboBoxItemStateChanged
        notifyModified();
    }//GEN-LAST:event_fileDialogsComboBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> fileDialogsComboBox;
    private javax.swing.JLabel fileDialogsLabel;
    // End of variables declaration//GEN-END:variables

    private void notifyModified() {
        if (settingsModifiedListener != null) {
            settingsModifiedListener.notifyModified();
        }
    }

    @Override
    public void setSettingsModifiedListener(SettingsModifiedListener listener) {
        settingsModifiedListener = listener;
    }

    private static int findMatchingElement(ComboBoxModel<String> model, String value) {
        for (int i = 0; i < model.getSize(); i++) {
            if (value.equals(model.getElementAt(i))) {
                return i;
            }
        }
        return -1;
    }
}
