rootProject.name = 'jaguif-addon-packs'

if (rootProject.path == ':') {
    include ':core:jaguif-core'
    include ':core:jaguif-basic'
    include ':core:jaguif-addon'
    include ':modules:jaguif-context-api'
    include ':modules:jaguif-contribution-api'
    include ':modules:jaguif-action-api'
    include ':modules:jaguif-help-api'
    include ':modules:jaguif-menu-api'
    include ':modules:jaguif-menu-popup-api'
    include ':modules:jaguif-tabpages-api'
    include ':modules:jaguif-addon-manager'
    include ':modules:jaguif-addon-manager-api'
    include ':modules:jaguif-language-api'
    include ':modules:jaguif-operation-api'
    include ':modules:jaguif-frame-api'
    include ':modules:jaguif-tabpages-api'
    include ':modules:jaguif-contribution-api'
    include ':modules:jaguif-context-api'
    include ':modules:jaguif-options-settings-api'
    include ':modules:jaguif-options-api'
    include ':modules:jaguif-utils'
    include ':modules:jaguif-window-api'

    include ':modules:jaguif-tabpages'
}

apply from: '../jaguif-modules-settings.gradle'
