/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.license.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ResourceBundle;
import org.jspecify.annotations.Nullable;
import org.jspecify.annotations.NullMarked;
import javax.swing.JComponent;
import org.exbin.jaguif.App;
import org.exbin.jaguif.language.api.ApplicationInfoKeys;
import org.exbin.jaguif.language.api.LanguageModuleApi;
import org.exbin.jaguif.utils.UiUtils;

/**
 * Basic about panel.
 */
@NullMarked
public class AboutPanel extends javax.swing.JPanel {

    protected final ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(AboutPanel.class);
    protected JComponent sideComponent = null;
    protected JComponent centerComponent = null;
    protected boolean darkMode = false;

    public AboutPanel() {
        initComponents();
        init();
    }

    private void init() {
        darkMode = UiUtils.isDarkUI();
        if (darkMode) {
            aboutHeaderPanel.setBackground(Color.BLACK);
            appTitleLabel.setForeground(Color.WHITE);
            appDescLabel.setForeground(Color.WHITE);
        }
    }

    public void loadFields() {
        LanguageModuleApi languageModule = App.getModule(LanguageModuleApi.class);
        ResourceBundle langBundle = languageModule.getAppBundle();
        if (langBundle.containsKey(ApplicationInfoKeys.APPLICATION_ABOUT_IMAGE)) {
            String aboutImagePath = langBundle.getString(ApplicationInfoKeys.APPLICATION_ABOUT_IMAGE);
            imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(aboutImagePath)));
            aboutHeaderPanel.add(aboutHeaderImagePanel, BorderLayout.WEST);
        }
        appTitleLabel.setText(langBundle.getString(ApplicationInfoKeys.APPLICATION_TITLE));
        appDescLabel.setText(langBundle.getString(ApplicationInfoKeys.APPLICATION_DESCRIPTION));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutHeaderImagePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        aboutHeaderPanel = new javax.swing.JPanel();
        headerSeparator = new javax.swing.JSeparator();
        aboutHeaderTitlePanel = new javax.swing.JPanel();
        appDescLabel = new javax.swing.JLabel();
        appTitleLabel = new javax.swing.JLabel();

        aboutHeaderImagePanel.setOpaque(false);

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout aboutHeaderImagePanelLayout = new javax.swing.GroupLayout(aboutHeaderImagePanel);
        aboutHeaderImagePanel.setLayout(aboutHeaderImagePanelLayout);
        aboutHeaderImagePanelLayout.setHorizontalGroup(
            aboutHeaderImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutHeaderImagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );
        aboutHeaderImagePanelLayout.setVerticalGroup(
            aboutHeaderImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        aboutHeaderPanel.setBackground(new java.awt.Color(255, 255, 255));
        aboutHeaderPanel.setLayout(new java.awt.BorderLayout());
        aboutHeaderPanel.add(headerSeparator, java.awt.BorderLayout.SOUTH);

        aboutHeaderTitlePanel.setOpaque(false);

        appDescLabel.setForeground(java.awt.Color.black);
        appDescLabel.setText(resourceBundle.getString("appDescLabel.text")); // NOI18N

        appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize()+4));
        appTitleLabel.setForeground(java.awt.Color.black);
        appTitleLabel.setText(resourceBundle.getString("appTitleLabel.text")); // NOI18N

        javax.swing.GroupLayout aboutHeaderTitlePanelLayout = new javax.swing.GroupLayout(aboutHeaderTitlePanel);
        aboutHeaderTitlePanel.setLayout(aboutHeaderTitlePanelLayout);
        aboutHeaderTitlePanelLayout.setHorizontalGroup(
            aboutHeaderTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(aboutHeaderTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutHeaderTitlePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(aboutHeaderTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(appDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(appTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        aboutHeaderTitlePanelLayout.setVerticalGroup(
            aboutHeaderTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
            .addGroup(aboutHeaderTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutHeaderTitlePanelLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(appTitleLabel)
                    .addGap(7, 7, 7)
                    .addComponent(appDescLabel)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        aboutHeaderPanel.add(aboutHeaderTitlePanel, java.awt.BorderLayout.CENTER);

        add(aboutHeaderPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutHeaderImagePanel;
    private javax.swing.JPanel aboutHeaderPanel;
    private javax.swing.JPanel aboutHeaderTitlePanel;
    private javax.swing.JLabel appDescLabel;
    private javax.swing.JLabel appTitleLabel;
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JLabel imageLabel;
    // End of variables declaration//GEN-END:variables

    public void setSideComponent(@Nullable JComponent sideComponent) {
        if (this.sideComponent != null) {
            remove(this.sideComponent);
        }

        if (sideComponent != null) {
            add(sideComponent, BorderLayout.WEST);
            this.sideComponent = sideComponent;
        }

        revalidate();
        repaint();
    }

    public void setCenterComponent(@Nullable JComponent centerComponent) {
        if (this.centerComponent != null) {
            remove(this.centerComponent);
        }

        if (centerComponent != null) {
            add(centerComponent, BorderLayout.CENTER);
            this.centerComponent = centerComponent;
        }

        revalidate();
        repaint();
    }
}
