rootProject.name = 'jaguif-context'

if (rootProject.path == ':') {
    include ':core:jaguif-core'
    include ':modules:jaguif-context-api'
    include ':modules:jaguif-contribution-api'
    include ':modules:jaguif-action-api'
    include ':modules:jaguif-language-api'
    include ':modules:jaguif-utils'
}

apply from: '../jaguif-modules-settings.gradle'
