/*
 * Copyright (C) ExBin Project, https://exbin.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.jaguif.addon.update.gui;

import java.net.URL;
import java.util.ResourceBundle;
import org.jspecify.annotations.NullMarked;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import org.exbin.jaguif.App;
import org.exbin.jaguif.addon.update.api.VersionNumbers;
import org.exbin.jaguif.addon.update.service.CheckForUpdateService;
import org.exbin.jaguif.utils.DesktopUtils;
import org.exbin.jaguif.language.api.LanguageModuleApi;

/**
 * Check for update panel.
 */
@NullMarked
public class CheckForUpdatePanel extends javax.swing.JPanel implements HyperlinkListener {

    private final ResourceBundle resourceBundle = App.getModule(LanguageModuleApi.class).getBundle(CheckForUpdatePanel.class);
    private CheckForUpdateService checkForUpdateService;
    private Controller controller;

    public CheckForUpdatePanel() {
        initComponents();
    }

    public ResourceBundle getResourceBundle() {
        return resourceBundle;
    }

    public void setController(Controller control) {
        this.controller = control;
    }

    public void setCheckForUpdateService(CheckForUpdateService checkForUpdateService) {
        this.checkForUpdateService = checkForUpdateService;

        URL downloadUrl = checkForUpdateService.getDownloadUrl();
        downloadButton.setEnabled(downloadUrl != null);
        recheckButton.setEnabled(true);

        setVersionNumbers(checkForUpdateService.getCurrentVersion());
        VersionNumbers updateVersion = checkForUpdateService.getUpdateVersion();
        if (updateVersion != null) {
            setUpdateVersionNumbers(updateVersion);
        }
    }

    public void performCheckForUpdate() {
        recheckButton.setEnabled(false);
        statusTextLabel.setText(resourceBundle.getString("status.checking.text"));
        statusIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(resourceBundle.getString("status.checking.icon"))));
        checkForUpdateService.performCheckForUpdates((CheckForUpdateService.CheckForUpdateResult result, VersionNumbers updateVersion) -> {
            if (updateVersion == null) {
                availableVersionTextField.setText(resourceBundle.getString("unknown"));
            } else {
                setUpdateVersionNumbers(updateVersion);
            }
            setCheckUpdatesResult(result);
            recheckButton.setEnabled(true);
        });
    }

    /**
     * Opens hyperlink in external browser.
     *
     * @param event hyperlink event
     */
    @Override
    public void hyperlinkUpdate(HyperlinkEvent event) {
        if (event.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            DesktopUtils.openDesktopURL(event.getURL().toExternalForm());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusPanel = new javax.swing.JPanel();
        statusIconLabel = new javax.swing.JLabel();
        statusTextLabel = new javax.swing.JLabel();
        currentVersionLabel = new javax.swing.JLabel();
        currentVersionTextField = new javax.swing.JTextField();
        availableVersionLabel = new javax.swing.JLabel();
        availableVersionTextField = new javax.swing.JTextField();
        recheckButton = new javax.swing.JButton();
        downloadButton = new javax.swing.JButton();

        statusPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        statusPanel.setMaximumSize(new java.awt.Dimension(32767, 60));
        statusPanel.setMinimumSize(new java.awt.Dimension(100, 60));

        statusIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/exbin/jaguif/addon/update/resources/icons/48px/internet-web-browser-7.png"))); // NOI18N

        statusTextLabel.setText(resourceBundle.getString("statusTextLabel.text")); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusIconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(statusTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusIconLabel)
                    .addComponent(statusTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        currentVersionLabel.setText(resourceBundle.getString("currentVersionLabel.text")); // NOI18N

        currentVersionTextField.setEditable(false);
        currentVersionTextField.setText("unknown");

        availableVersionLabel.setText(resourceBundle.getString("availableVersionLabel.text")); // NOI18N

        availableVersionTextField.setEditable(false);
        availableVersionTextField.setText("unknown");

        recheckButton.setText(resourceBundle.getString("recheckButton.text")); // NOI18N
        recheckButton.setEnabled(false);
        recheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recheckButtonActionPerformed(evt);
            }
        });

        downloadButton.setText(resourceBundle.getString("downloadButton.text")); // NOI18N
        downloadButton.setEnabled(false);
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentVersionTextField)
                    .addComponent(availableVersionTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentVersionLabel)
                            .addComponent(availableVersionLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(downloadButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(recheckButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentVersionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentVersionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(availableVersionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(availableVersionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recheckButton)
                    .addComponent(downloadButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void recheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recheckButtonActionPerformed
        performCheckForUpdate();
    }//GEN-LAST:event_recheckButtonActionPerformed

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        DesktopUtils.openDesktopURL(checkForUpdateService.getDownloadUrl());
    }//GEN-LAST:event_downloadButtonActionPerformed

    private void setVersionNumbers(VersionNumbers versionNumbers) {
        currentVersionTextField.setText(versionNumbers.versionAsString());
    }

    private void setUpdateVersionNumbers(VersionNumbers versionNumbers) {
        availableVersionTextField.setText(versionNumbers.versionAsString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availableVersionLabel;
    private javax.swing.JTextField availableVersionTextField;
    private javax.swing.JLabel currentVersionLabel;
    private javax.swing.JTextField currentVersionTextField;
    private javax.swing.JButton downloadButton;
    private javax.swing.JButton recheckButton;
    private javax.swing.JLabel statusIconLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JLabel statusTextLabel;
    // End of variables declaration//GEN-END:variables

    public void setCheckUpdatesResult(CheckForUpdateService.CheckForUpdateResult result) {
        if (result == null) {
            return;
        }
        switch (result) {
            case UPDATE_URL_NOT_SET: {
                statusTextLabel.setText(resourceBundle.getString("status.updateUrlNotSet.text"));
                statusIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(resourceBundle.getString("status.updateUrlNotSet.icon"))));
                break;
            }
            case NO_CONNECTION: {
                statusTextLabel.setText(resourceBundle.getString("status.noConnection.text"));
                statusIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(resourceBundle.getString("status.noConnection.icon"))));
                break;
            }
            case CONNECTION_ISSUE: {
                statusTextLabel.setText(resourceBundle.getString("status.connectionIssue.text"));
                statusIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(resourceBundle.getString("status.connectionIssue.icon"))));
                break;
            }
            case NOT_FOUND: {
                statusTextLabel.setText(resourceBundle.getString("status.notFound.text"));
                statusIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(resourceBundle.getString("status.notFound.icon"))));
                break;
            }
            case NO_UPDATE_AVAILABLE: {
                statusTextLabel.setText(resourceBundle.getString("status.noUpdateAvailable.text"));
                statusIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(resourceBundle.getString("status.noUpdateAvailable.icon"))));
                break;
            }
            case UPDATE_FOUND: {
                statusTextLabel.setText(resourceBundle.getString("status.updateFound.text"));
                statusIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(resourceBundle.getString("status.updateFound.icon"))));
                break;
            }
            default: {
                statusTextLabel.setText("Unexpected result state " + result.name() + "!");
                statusIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(resourceBundle.getString("status.misc.icon"))));
                break;
            }
        }
    }

    public interface Controller {

        void checkForUpdate();
    }
}
